version: "3.9"
services:
  pythondev:
    container_name: CHS_DOWNLOADER_DEV
    image: python:latest
    volumes:
      - .:/workspaces/chs-downloader
    working_dir: /workspaces/chs-downloader
    command:
      - bash
      - -c
      - |
        pip install -r requirements.txt
        bash
    tty: true
